//
//  AgentSkill.swift
//  AuroraAgent
//
//  Created by Dan Murrell Jr on 3/25/25.
//


import Foundation

// MARK: - AgentSkill Protocol

/// Represents a capability that an agent can perform.
public protocol AgentSkill {
    /// A unique identifier for the skill.
    var id: UUID { get }
    
    /// The name of the skill.
    var name: String { get }
    
    /// A description of what the skill does.
    var description: String { get }

    /**
        Executes the skill without a query.

        - Returns: A string result generated by the skill.
     */
    func execute() async throws -> String

    /**
     Executes the skill with a given query.
     
     - Parameters:
        - query: The instruction or prompt for the skill.
        - memory: An optional shared memory that the agent can use.
     
     - Returns: A string result generated by the skill.
     
     - Throws: An error if execution fails.
     */
    func execute(query: String, memory: AgentMemory?) async throws -> String
}

public extension AgentSkill {
    func execute() async throws -> String {
        return try await execute(query: "", memory: nil)
    }
}
