name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Swift
        uses: actions/setup-swift@v1
        with:
          swift-version: '5.10'

      - name: Build
        run: swift build

      - name: Test
        run: swift test

      - name: Install SwiftLint
        if: runner.os == 'macOS'
        run: brew install swiftlint

      - name: SwiftLint Lint
        if: runner.os == 'macOS'
        run: swiftlint lint --strict